AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Job FinalGlue

Parameters:
  ScriptBucket: {Type: String}
  ScriptKey: {Type: String}

Resources:

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: FinalGlue
      Role: !GetAtt GlueRole.Arn
      GlueVersion: "4.0"

      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${ScriptBucket}/${ScriptKey}

      WorkerType: G.1X
      NumberOfWorkers: 10
      Timeout: 120
