AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda + S3 Trigger for Glue Pipeline

Parameters:
  LambdaName:
    Type: String
    Default: airline-and-airport

  CodeBucket:
    Type: String

  CodeKey:
    Type: String

  DataBucketName:
    Type: String
    Default: airport-airline-operations-analytics-platform


Resources:

# ---------------- IAM ROLE ----------------

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: GlueAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetCrawler
                  - glue:StartCrawler
                Resource: "*"


# ---------------- LAMBDA ----------------

  GlueTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Runtime: python3.9
      Handler: lambda.lambda_handler
      Timeout: 900
      MemorySize: 256
      Role: !GetAtt LambdaRole.Arn

      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey


# ---------------- PERMISSION ----------------

  AllowS3Invoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GlueTriggerLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${DataBucketName}


# ---------------- S3 TRIGGER ----------------

  S3Trigger:
    Type: AWS::S3::BucketNotification
    DependsOn: AllowS3Invoke
    Properties:
      Bucket: !Ref DataBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt GlueTriggerLambda.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: raw/


Outputs:

  LambdaArn:
    Value: !GetAtt GlueTriggerLambda.Arn
