AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ScriptBucket:
    Type: String
  ScriptKey:
    Type: String
  JobName:
    Type: String

Resources:

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue-cicd-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: "*"


  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref JobName
      Role: !GetAtt GlueRole.Arn

      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${ScriptBucket}/${ScriptKey}
        PythonVersion: 3

      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 60
