name: Deploy Glue ETL & Infra

on:
  push:
    branches: [ main ]

jobs:
  deploy-etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Glue ETL scripts
        run: |
          aws s3 cp etl/etl_customers.py s3://amzn-s3-finalproject-glue-scripts/etl_customers.py
          aws s3 cp etl/etl_congestion_score.py s3://amzn-s3-finalproject-glue-scripts/etl_congestion_score.py
